export type { DependencyGraph, GraphNode, GraphEdge, ImpactResult, NodeType, EdgeType, ModuleCluster, RiskLevel, ClassifiedImpact } from './types.js'
export { GraphBuilder } from './graph-builder.js'
export { ImpactAnalyzer } from './impact-analyzer.js'
export { ClusterDetector } from './cluster-detector.js'
export { DeadCodeDetector } from './dead-code-detector.js'
export type { DeadCodeResult, DeadCodeEntry } from './dead-code-detector.js'
export { RiskEngine } from './risk-engine.js'
export type { RiskContext, RiskModifiers } from './risk-engine.js'
export { ConfidenceEngine } from './confidence-engine.js'
export { QueryEngine } from './query-engine.js'
export { RichFunctionIndex } from './rich-function-index.js'
export type { RichFunction, RichParam, RichCall, RichErrorHandling, SearchQuery, SearchResult, ContextRequest, FunctionContext } from './rich-function-index.js'

