export { IntentInterpreter } from './interpreter.js'
export { ConflictDetector } from './conflict-detector.js'
export { Suggester } from './suggester.js'
export { PreflightPipeline } from './preflight.js'
export { SemanticSearcher } from './semantic-searcher.js'
export { EmbeddingManager } from './embedding-manager.js'
export { IntentUnderstanding } from './intent-understanding.js'
export { AutoCorrectionEngine } from './auto-correction.js'
export { EnforcedSafetyGates } from './enforced-safety.js'
export { PreEditValidation } from './pre-edit-validation.js'

export type { SemanticMatch } from './semantic-searcher.js'
export type { IntentContext, IntentAnalysis } from './intent-understanding.js'
export type { CorrectionIssue, CorrectionResult } from './auto-correction.js'
export type { SafetyGateResult, SafetyGateConfig } from './enforced-safety.js'
export type { EditProposal, ValidationResult } from './pre-edit-validation.js'

export type { Intent, Conflict, ConflictResult, Suggestion, PreflightResult, AIProviderConfig } from './types.js'
export { IntentSchema } from './types.js'
