%%{init: {"theme": "base", "themeVariables": {"primaryColor": "#1e293b", "primaryTextColor": "#e2e8f0", "lineColor": "#64748b", "secondaryColor": "#334155", "tertiaryColor": "#475569", "background": "#0f172a", "mainBkg": "#1e293b", "nodeBorder": "#475569"}}}%%
graph TD

    subgraph mod_app["📦 app"]
        fn_app_layout_tsx_RootLayout["🚀 RootLayout<br/>(Entry)"]
        fn_app_page_tsx_Page["🚀 Page<br/>(Entry)"]
    end
    subgraph mod_components["📦 components"]
        fn_components_code_block_command_tsx_CodeBlockCommand["🚀 CodeBlockCommand<br/>(Entry)"]
        fn_components_code_block_figure_tsx_CopyButton["🚀 CopyButton<br/>(Entry)"]
        fn_components_code_block_figure_tsx_CodeBlockFigure["🚀 CodeBlockFigure<br/>(Entry)"]
        fn_components_code_collapsible_wrapper_tsx_CodeCollapsibleWrapper["🚀 CodeCollapsibleWrapper<br/>(Entry)"]
        fn_components_code_tabs_tsx_CodeTabs["🚀 CodeTabs<br/>(Entry)"]
        fn_components_collapsible_list_tsx_CollapsibleList["🚀 CollapsibleList<br/>(Entry)"]
        fn_components_command_menu_tsx_CommandMenu["🚀 CommandMenu<br/>(Entry)"]
        fn_components_command_menu_tsx_CommandMenuInput["🚀 CommandMenuInput<br/>(Entry)"]
        fn_components_command_menu_tsx_CommandLinkGroup["🚀 CommandLinkGroup<br/>(Entry)"]
        fn_components_command_menu_tsx_buildCommandMetaMap["🚀 buildCommandMetaMap<br/>(Entry)"]
        fn_components_command_menu_tsx_CommandMenuFooter["🚀 CommandMenuFooter<br/>(Entry)"]
        fn_components_command_menu_tsx_postToCommandLinkItem["🚀 postToCommandLinkItem<br/>(Entry)"]
        fn_components_consent_manager_client_tsx_ConsentManagerClient["🚀 ConsentManagerClient<br/>(Entry)"]
        fn_components_consent_manager_tsx_ConsentManager["🚀 ConsentManager<br/>(Entry)"]
        fn_components_copy_button_tsx_CopyButton["🚀 CopyButton<br/>(Entry)"]
        fn_components_copy_markdown_button_tsx_CopyMarkdownButton["🚀 CopyMarkdownButton<br/>(Entry)"]
        fn_components_header_tsx_ThemeToggle["🚀 ThemeToggle<br/>(Entry)"]
        fn_components_header_tsx_Header["🚀 Header<br/>(Entry)"]
        fn_components_markdown_tsx_Markdown["🚀 Markdown<br/>(Entry)"]
        fn_components_mdx_copy_tsx_MDX["🚀 MDX<br/>(Entry)"]
        fn_components_mdx_tsx_pre["🚀 pre<br/>(Entry)"]
        fn_components_mdx_tsx_code["🚀 code<br/>(Entry)"]
        fn_components_mdx_tsx_h1["🚀 h1<br/>(Entry)"]
        fn_components_mdx_tsx_h2["🚀 h2<br/>(Entry)"]
        fn_components_mdx_tsx_h3["🚀 h3<br/>(Entry)"]
        fn_components_mdx_tsx_h4["🚀 h4<br/>(Entry)"]
        fn_components_mdx_tsx_p["🚀 p<br/>(Entry)"]
        fn_components_mdx_tsx_ul["🚀 ul<br/>(Entry)"]
        fn_components_mdx_tsx_ol["🚀 ol<br/>(Entry)"]
        fn_components_mdx_tsx_li["🚀 li<br/>(Entry)"]
        fn_components_mdx_tsx_blockquote["🚀 blockquote<br/>(Entry)"]
        fn_components_mdx_tsx_table["🚀 table<br/>(Entry)"]
        fn_components_mdx_tsx_thead["🚀 thead<br/>(Entry)"]
        fn_components_mdx_tsx_tbody["🚀 tbody<br/>(Entry)"]
        fn_components_mdx_tsx_tr["🚀 tr<br/>(Entry)"]
        fn_components_mdx_tsx_th["🚀 th<br/>(Entry)"]
        fn_components_mdx_tsx_td["🚀 td<br/>(Entry)"]
        fn_components_mdx_tsx_hr["🚀 hr<br/>(Entry)"]
        fn_components_mdx_tsx_strong["🚀 strong<br/>(Entry)"]
        fn_components_mdx_tsx_em["🚀 em<br/>(Entry)"]
        fn_components_mdx_tsx_a["🚀 a<br/>(Entry)"]
        fn_components_mdx_tsx_getMDXComponents["🚀 getMDXComponents<br/>(Entry)"]
        fn_components_not_found_tsx_NotFound["🚀 NotFound<br/>(Entry)"]
        fn_components_search_dialog_tsx_stripMark["🚀 stripMark<br/>(Entry)"]
        fn_components_search_dialog_tsx_Highlighted["🚀 Highlighted<br/>(Entry)"]
        fn_components_search_dialog_tsx_SearchDialog["🚀 SearchDialog<br/>(Entry)"]
        fn_components_sidebar_tsx_SidebarContents["🚀 SidebarContents<br/>(Entry)"]
        fn_components_sidebar_tsx_Sidebar["🚀 Sidebar<br/>(Entry)"]
        fn_components_sidebar_tsx_MobileSidebarTrigger["🚀 MobileSidebarTrigger<br/>(Entry)"]
        fn_components_sidebar_tsx_SidebarItem["🚀 SidebarItem<br/>(Entry)"]
        fn_components_toc_tsx_TOC["🚀 TOC<br/>(Entry)"]
        fn_components_toc_tsx_SlidingPip["🚀 SlidingPip<br/>(Entry)"]
        fn_components_ui_breadcrumb_tsx_Breadcrumb["🚀 Breadcrumb<br/>(Entry)"]
        fn_components_ui_breadcrumb_tsx_BreadcrumbList["🚀 BreadcrumbList<br/>(Entry)"]
        fn_components_ui_breadcrumb_tsx_BreadcrumbItem["🚀 BreadcrumbItem<br/>(Entry)"]
        fn_components_ui_breadcrumb_tsx_BreadcrumbLink["🚀 BreadcrumbLink<br/>(Entry)"]
        fn_components_ui_breadcrumb_tsx_BreadcrumbPage["🚀 BreadcrumbPage<br/>(Entry)"]
        fn_components_ui_breadcrumb_tsx_BreadcrumbSeparator["🚀 BreadcrumbSeparator<br/>(Entry)"]
        fn_components_ui_breadcrumb_tsx_BreadcrumbEllipsis["🚀 BreadcrumbEllipsis<br/>(Entry)"]
        fn_components_ui_button_tsx_Button["🚀 Button<br/>(Entry)"]
        fn_components_ui_button_1_tsx_Button["🚀 Button<br/>(Entry)"]
        fn_components_ui_collapsible_tsx_Collapsible["🚀 Collapsible<br/>(Entry)"]
        fn_components_ui_collapsible_tsx_CollapsibleTrigger["🚀 CollapsibleTrigger<br/>(Entry)"]
        fn_components_ui_collapsible_tsx_CollapsibleContent["🚀 CollapsibleContent<br/>(Entry)"]
        fn_components_ui_collapsible_tsx_CollapsibleWithContext["🚀 CollapsibleWithContext<br/>(Entry)"]
        fn_components_ui_collapsible_tsx_CollapsibleChevronsIcon["🚀 CollapsibleChevronsIcon<br/>(Entry)"]
        fn_components_ui_command_tsx_Command["🚀 Command<br/>(Entry)"]
        fn_components_ui_command_tsx_CommandDialog["🚀 CommandDialog<br/>(Entry)"]
        fn_components_ui_command_tsx_CommandInput["🚀 CommandInput<br/>(Entry)"]
        fn_components_ui_command_tsx_CommandList["🚀 CommandList<br/>(Entry)"]
        fn_components_ui_command_tsx_CommandEmpty["🚀 CommandEmpty<br/>(Entry)"]
        fn_components_ui_command_tsx_CommandGroup["🚀 CommandGroup<br/>(Entry)"]
        fn_components_ui_command_tsx_CommandSeparator["🚀 CommandSeparator<br/>(Entry)"]
        fn_components_ui_command_tsx_CommandItem["🚀 CommandItem<br/>(Entry)"]
        fn_components_ui_command_tsx_CommandShortcut["🚀 CommandShortcut<br/>(Entry)"]
        fn_components_ui_context_menu_tsx_ContextMenu["🚀 ContextMenu<br/>(Entry)"]
        fn_components_ui_context_menu_tsx_ContextMenuTrigger["🚀 ContextMenuTrigger<br/>(Entry)"]
        fn_components_ui_context_menu_tsx_ContextMenuGroup["🚀 ContextMenuGroup<br/>(Entry)"]
        fn_components_ui_context_menu_tsx_ContextMenuPortal["🚀 ContextMenuPortal<br/>(Entry)"]
        fn_components_ui_context_menu_tsx_ContextMenuSub["🚀 ContextMenuSub<br/>(Entry)"]
        fn_components_ui_context_menu_tsx_ContextMenuRadioGroup["🚀 ContextMenuRadioGroup<br/>(Entry)"]
        fn_components_ui_context_menu_tsx_ContextMenuSubTrigger["🚀 ContextMenuSubTrigger<br/>(Entry)"]
        fn_components_ui_context_menu_tsx_ContextMenuSubContent["🚀 ContextMenuSubContent<br/>(Entry)"]
        fn_components_ui_context_menu_tsx_ContextMenuContent["🚀 ContextMenuContent<br/>(Entry)"]
        fn_components_ui_context_menu_tsx_ContextMenuItem["🚀 ContextMenuItem<br/>(Entry)"]
        fn_components_ui_context_menu_tsx_ContextMenuCheckboxItem["🚀 ContextMenuCheckboxItem<br/>(Entry)"]
        fn_components_ui_context_menu_tsx_ContextMenuRadioItem["🚀 ContextMenuRadioItem<br/>(Entry)"]
        fn_components_ui_context_menu_tsx_ContextMenuLabel["🚀 ContextMenuLabel<br/>(Entry)"]
        fn_components_ui_context_menu_tsx_ContextMenuSeparator["🚀 ContextMenuSeparator<br/>(Entry)"]
        fn_components_ui_context_menu_tsx_ContextMenuShortcut["🚀 ContextMenuShortcut<br/>(Entry)"]
        fn_components_ui_dialog_tsx_Dialog["🚀 Dialog<br/>(Entry)"]
        fn_components_ui_dialog_tsx_DialogTrigger["🚀 DialogTrigger<br/>(Entry)"]
        fn_components_ui_dialog_tsx_DialogPortal["🚀 DialogPortal<br/>(Entry)"]
        fn_components_ui_dialog_tsx_DialogClose["🚀 DialogClose<br/>(Entry)"]
        fn_components_ui_dialog_tsx_DialogOverlay["🚀 DialogOverlay<br/>(Entry)"]
        fn_components_ui_dialog_tsx_DialogContent["🚀 DialogContent<br/>(Entry)"]
        fn_components_ui_dialog_tsx_DialogHeader["🚀 DialogHeader<br/>(Entry)"]
        fn_components_ui_dialog_tsx_DialogFooter["🚀 DialogFooter<br/>(Entry)"]
        fn_components_ui_dialog_tsx_DialogTitle["🚀 DialogTitle<br/>(Entry)"]
        fn_components_ui_dialog_tsx_DialogDescription["🚀 DialogDescription<br/>(Entry)"]
        fn_components_ui_dropdown_menu_tsx_DropdownMenu["🚀 DropdownMenu<br/>(Entry)"]
        fn_components_ui_dropdown_menu_tsx_DropdownMenuPortal["🚀 DropdownMenuPortal<br/>(Entry)"]
        fn_components_ui_dropdown_menu_tsx_DropdownMenuTrigger["🚀 DropdownMenuTrigger<br/>(Entry)"]
        fn_components_ui_dropdown_menu_tsx_DropdownMenuContent["🚀 DropdownMenuContent<br/>(Entry)"]
        fn_components_ui_dropdown_menu_tsx_DropdownMenuGroup["🚀 DropdownMenuGroup<br/>(Entry)"]
        fn_components_ui_dropdown_menu_tsx_DropdownMenuItem["🚀 DropdownMenuItem<br/>(Entry)"]
        fn_components_ui_dropdown_menu_tsx_DropdownMenuCheckboxItem["🚀 DropdownMenuCheckboxItem<br/>(Entry)"]
        fn_components_ui_dropdown_menu_tsx_DropdownMenuRadioGroup["🚀 DropdownMenuRadioGroup<br/>(Entry)"]
        fn_components_ui_dropdown_menu_tsx_DropdownMenuRadioItem["🚀 DropdownMenuRadioItem<br/>(Entry)"]
        fn_components_ui_dropdown_menu_tsx_DropdownMenuLabel["🚀 DropdownMenuLabel<br/>(Entry)"]
        fn_components_ui_dropdown_menu_tsx_DropdownMenuSeparator["🚀 DropdownMenuSeparator<br/>(Entry)"]
        fn_components_ui_dropdown_menu_tsx_DropdownMenuShortcut["🚀 DropdownMenuShortcut<br/>(Entry)"]
        fn_components_ui_dropdown_menu_tsx_DropdownMenuSub["🚀 DropdownMenuSub<br/>(Entry)"]
        fn_components_ui_dropdown_menu_tsx_DropdownMenuSubTrigger["🚀 DropdownMenuSubTrigger<br/>(Entry)"]
        fn_components_ui_dropdown_menu_tsx_DropdownMenuSubContent["🚀 DropdownMenuSubContent<br/>(Entry)"]
        fn_components_ui_form_tsx_FormField["🚀 FormField<br/>(Entry)"]
        fn_components_ui_form_tsx_FormItem["🚀 FormItem<br/>(Entry)"]
        fn_components_ui_form_tsx_FormLabel["🚀 FormLabel<br/>(Entry)"]
        fn_components_ui_form_tsx_FormControl["🚀 FormControl<br/>(Entry)"]
        fn_components_ui_form_tsx_FormDescription["🚀 FormDescription<br/>(Entry)"]
        fn_components_ui_form_tsx_FormMessage["🚀 FormMessage<br/>(Entry)"]
        fn_components_ui_input_group_tsx_InputGroup["🚀 InputGroup<br/>(Entry)"]
        fn_components_ui_input_group_tsx_InputGroupAddon["🚀 InputGroupAddon<br/>(Entry)"]
        fn_components_ui_input_group_tsx_InputGroupButton["🚀 InputGroupButton<br/>(Entry)"]
        fn_components_ui_input_group_tsx_InputGroupText["🚀 InputGroupText<br/>(Entry)"]
        fn_components_ui_input_group_tsx_InputGroupInput["🚀 InputGroupInput<br/>(Entry)"]
        fn_components_ui_input_group_tsx_InputGroupTextarea["🚀 InputGroupTextarea<br/>(Entry)"]
        fn_components_ui_input_tsx_Input["🚀 Input<br/>(Entry)"]
        fn_components_ui_kbd_tsx_Kbd["🚀 Kbd<br/>(Entry)"]
        fn_components_ui_kbd_tsx_KbdGroup["🚀 KbdGroup<br/>(Entry)"]
        fn_components_ui_label_tsx_Label["🚀 Label<br/>(Entry)"]
        fn_components_ui_navigation_menu_tsx_NavigationMenu["🚀 NavigationMenu<br/>(Entry)"]
        fn_components_ui_navigation_menu_tsx_NavigationMenuList["🚀 NavigationMenuList<br/>(Entry)"]
        fn_components_ui_navigation_menu_tsx_NavigationMenuItem["🚀 NavigationMenuItem<br/>(Entry)"]
        fn_components_ui_navigation_menu_tsx_NavigationMenuTrigger["🚀 NavigationMenuTrigger<br/>(Entry)"]
        fn_components_ui_navigation_menu_tsx_NavigationMenuContent["🚀 NavigationMenuContent<br/>(Entry)"]
        fn_components_ui_navigation_menu_tsx_NavigationMenuViewport["🚀 NavigationMenuViewport<br/>(Entry)"]
        fn_components_ui_navigation_menu_tsx_NavigationMenuLink["🚀 NavigationMenuLink<br/>(Entry)"]
        fn_components_ui_navigation_menu_tsx_NavigationMenuIndicator["🚀 NavigationMenuIndicator<br/>(Entry)"]
        fn_components_ui_scroll_area_copy_tsx_ScrollArea["🚀 ScrollArea<br/>(Entry)"]
        fn_components_ui_scroll_area_copy_tsx_ScrollBar["🚀 ScrollBar<br/>(Entry)"]
        fn_components_ui_scroll_area_tsx_ScrollArea["🚀 ScrollArea<br/>(Entry)"]
        fn_components_ui_scroll_area_tsx_ScrollBar["🚀 ScrollBar<br/>(Entry)"]
        fn_components_ui_separator_tsx_Separator["🚀 Separator<br/>(Entry)"]
        fn_components_ui_sheet_tsx_Sheet["🚀 Sheet<br/>(Entry)"]
        fn_components_ui_sheet_tsx_SheetTrigger["🚀 SheetTrigger<br/>(Entry)"]
        fn_components_ui_sheet_tsx_SheetClose["🚀 SheetClose<br/>(Entry)"]
        fn_components_ui_sheet_tsx_SheetPortal["🚀 SheetPortal<br/>(Entry)"]
        fn_components_ui_sheet_tsx_SheetOverlay["🚀 SheetOverlay<br/>(Entry)"]
        fn_components_ui_sheet_tsx_SheetContent["🚀 SheetContent<br/>(Entry)"]
        fn_components_ui_sheet_tsx_SheetHeader["🚀 SheetHeader<br/>(Entry)"]
        fn_components_ui_sheet_tsx_SheetFooter["🚀 SheetFooter<br/>(Entry)"]
        fn_components_ui_sheet_tsx_SheetTitle["🚀 SheetTitle<br/>(Entry)"]
        fn_components_ui_sheet_tsx_SheetDescription["🚀 SheetDescription<br/>(Entry)"]
        fn_components_ui_sonner_tsx_Toaster["🚀 Toaster<br/>(Entry)"]
        fn_components_ui_table_tsx_Table["🚀 Table<br/>(Entry)"]
        fn_components_ui_table_tsx_TableHeader["🚀 TableHeader<br/>(Entry)"]
        fn_components_ui_table_tsx_TableBody["🚀 TableBody<br/>(Entry)"]
        fn_components_ui_table_tsx_TableRow["🚀 TableRow<br/>(Entry)"]
        fn_components_ui_table_tsx_TableHead["🚀 TableHead<br/>(Entry)"]
        fn_components_ui_table_tsx_TableCell["🚀 TableCell<br/>(Entry)"]
        fn_components_ui_tabs_tsx_Tabs["🚀 Tabs<br/>(Entry)"]
        fn_components_ui_tabs_tsx_TabsList["🚀 TabsList<br/>(Entry)"]
        fn_components_ui_tabs_tsx_TabsTrigger["🚀 TabsTrigger<br/>(Entry)"]
        fn_components_ui_tabs_tsx_TabsContent["🚀 TabsContent<br/>(Entry)"]
        fn_components_ui_tag_tsx_Tag["🚀 Tag<br/>(Entry)"]
        fn_components_ui_textarea_tsx_Textarea["🚀 Textarea<br/>(Entry)"]
        fn_components_ui_tooltip_tsx_TooltipProvider["🚀 TooltipProvider<br/>(Entry)"]
        fn_components_ui_tooltip_tsx_Tooltip["🚀 Tooltip<br/>(Entry)"]
        fn_components_ui_tooltip_tsx_TooltipTrigger["🚀 TooltipTrigger<br/>(Entry)"]
        fn_components_ui_tooltip_tsx_TooltipContent["🚀 TooltipContent<br/>(Entry)"]
        fn_components_ui_typography_tsx_Prose["🚀 Prose<br/>(Entry)"]
        fn_components_ui_typography_tsx_ProseMono["🚀 ProseMono<br/>(Entry)"]
        fn_components_ui_typography_tsx_Code["🚀 Code<br/>(Entry)"]
        fn_components_ui_typography_tsx_Heading["🚀 Heading<br/>(Entry)"]
        fn_components_base_ui_tabs_tsx_Tabs["🚀 Tabs<br/>(Entry)"]
        fn_components_base_ui_tabs_tsx_TabsList["🚀 TabsList<br/>(Entry)"]
        fn_components_base_ui_tabs_tsx_TabsIndicator["🚀 TabsIndicator<br/>(Entry)"]
        fn_components_base_ui_tabs_tsx_TabsTrigger["🚀 TabsTrigger<br/>(Entry)"]
        fn_components_base_ui_tabs_tsx_TabsContent["🚀 TabsContent<br/>(Entry)"]
        fn_components_base_ui_tooltip_tsx_TooltipProvider["🚀 TooltipProvider<br/>(Entry)"]
        fn_components_base_ui_tooltip_tsx_TooltipRoot["🚀 TooltipRoot<br/>(Entry)"]
        fn_components_base_ui_tooltip_tsx_Tooltip["🚀 Tooltip<br/>(Entry)"]
        fn_components_base_ui_tooltip_tsx_TooltipTrigger["🚀 TooltipTrigger<br/>(Entry)"]
        fn_components_base_ui_tooltip_tsx_TooltipContent["🚀 TooltipContent<br/>(Entry)"]
    end
    subgraph mod_lib["📦 lib"]
        fn_lib_events_ts_trackEvent["🚀 trackEvent<br/>(Entry)"]
        fn_lib_layout_shared_tsx_baseOptions["🚀 baseOptions<br/>(Entry)"]
        fn_lib_utils_ts_cn["🚀 cn<br/>(Entry)"]
    end
    subgraph mod_providers["📦 providers"]
        fn_providers_fuma_provider_tsx_RootLayout["🚀 RootLayout<br/>(Entry)"]
        fn_providers_providers_tsx_providers["🚀 providers<br/>(Entry)"]
        fn_providers_theme_provider_tsx_ThemeProvider["🚀 ThemeProvider<br/>(Entry)"]
        fn_providers_theme_provider_tsx_ThemeHotkey["🚀 ThemeHotkey<br/>(Entry)"]
    end
    subgraph mod_app_docs["📦 app-docs"]
        fn_app_docs_layout_tsx_DocsLayout["🚀 DocsLayout<br/>(Entry)"]
    end
    subgraph mod_components_kibo_ui_image_zoom["📦 components-kibo-ui-image-zoom"]
        fn_components_kibo_ui_image_zoom_index_tsx_ImageZoom["🚀 ImageZoom<br/>(Entry)"]
        fn_components_kibo_ui_marquee_index_tsx_Marquee["🚀 Marquee<br/>(Entry)"]
        fn_components_kibo_ui_marquee_index_tsx_MarqueeContent["🚀 MarqueeContent<br/>(Entry)"]
        fn_components_kibo_ui_marquee_index_tsx_MarqueeFade["🚀 MarqueeFade<br/>(Entry)"]
        fn_components_kibo_ui_marquee_index_tsx_MarqueeItem["🚀 MarqueeItem<br/>(Entry)"]
        fn_components_kibo_ui_contribution_graph_index_tsx_ContributionGraph["🚀 ContributionGraph<br/>(Entry)"]
        fn_components_kibo_ui_contribution_graph_index_tsx_ContributionGraphBlock["🚀 ContributionGraphBlock<br/>(Entry)"]
        fn_components_kibo_ui_contribution_graph_index_tsx_ContributionGraphCalendar["🚀 ContributionGraphCalendar<br/>(Entry)"]
        fn_components_kibo_ui_contribution_graph_index_tsx_ContributionGraphFooter["🚀 ContributionGraphFooter<br/>(Entry)"]
        fn_components_kibo_ui_contribution_graph_index_tsx_ContributionGraphTotalCount["🚀 ContributionGraphTotalCount<br/>(Entry)"]
        fn_components_kibo_ui_contribution_graph_index_tsx_ContributionGraphLegend["🚀 ContributionGraphLegend<br/>(Entry)"]
    end
    subgraph mod_unknown["📦 unknown"]
        fn_app_docs______slug___page_tsx_Page["🚀 Page<br/>(Entry)"]
        fn_app_docs______slug___page_tsx_generateStaticParams["🚀 generateStaticParams<br/>(Entry)"]
        fn_app_docs______slug___page_tsx_generateMetadata["🚀 generateMetadata<br/>(Entry)"]
    end

    fn_components_copy_button_tsx_CopyButton --> fn_components_copy_button_tsx_copyToClipboardWithEvent["copyToClipboardWithEvent"]
    fn_components_header_tsx_Header --> fn_components_header_tsx_useBreadcrumbs["useBreadcrumbs"]
    fn_components_sidebar_tsx_SidebarItem --> fn_components_sidebar_tsx_getIcon["getIcon"]
    fn_providers_theme_provider_tsx_ThemeHotkey --> fn_providers_theme_provider_tsx_isTypingTarget["isTypingTarget"]
    fn_components_ui_collapsible_tsx_CollapsibleChevronsIcon --> fn_components_ui_collapsible_tsx_useCollapsible["useCollapsible"]
    fn_components_ui_form_tsx_FormLabel --> fn_components_ui_form_tsx_useFormField["useFormField"]
    fn_components_ui_form_tsx_FormControl --> fn_components_ui_form_tsx_useFormField["useFormField"]
    fn_components_ui_form_tsx_FormDescription --> fn_components_ui_form_tsx_useFormField["useFormField"]
    fn_components_ui_form_tsx_FormMessage --> fn_components_ui_form_tsx_useFormField["useFormField"]
    fn_components_kibo_ui_contribution_graph_index_tsx_ContributionGraph --> fn_components_kibo_ui_contribution_graph_index_tsx_groupByWeeks["groupByWeeks"]
    fn_components_kibo_ui_contribution_graph_index_tsx_ContributionGraphBlock --> fn_components_kibo_ui_contribution_graph_index_tsx_useContributionGraph["useContributionGraph"]
    fn_components_kibo_ui_contribution_graph_index_tsx_ContributionGraphCalendar --> fn_components_kibo_ui_contribution_graph_index_tsx_useContributionGraph["useContributionGraph"]
    fn_components_kibo_ui_contribution_graph_index_tsx_ContributionGraphCalendar --> fn_components_kibo_ui_contribution_graph_index_tsx_getMonthLabels["getMonthLabels"]
    fn_components_kibo_ui_contribution_graph_index_tsx_ContributionGraphTotalCount --> fn_components_kibo_ui_contribution_graph_index_tsx_useContributionGraph["useContributionGraph"]
    fn_components_kibo_ui_contribution_graph_index_tsx_ContributionGraphLegend --> fn_components_kibo_ui_contribution_graph_index_tsx_useContributionGraph["useContributionGraph"]

    classDef default fill:#334155,stroke:#64748b,color:#e2e8f0